### ISSUE TITLE
convert_loc_to_rs() - Prevent error when "strand" column is passed by the user

### ISSUE THREAD

**Issue by AMCalejandro** [RHReynolds/colochelpR#3]
I found something else it could be enhanced on the convert_loc_to_rs()
If the user passes a df with strand, when trying to remove the strand column poping downstream as a result of making a GRanges df. In this case, you won't have strand but quite likely you would have strand.x and strand.y?

<pre>&gt; convert_loc_to_rs
function (df, dbSNP) 
{
    if (stringr::str_detect(df$CHR[1], &quot;chr&quot;)) {
        df &lt;- df %&gt;% dplyr::mutate(CHR = stringr::str_replace(CHR, 
            &quot;chr&quot;, &quot;&quot;))
    }
    df &lt;- df %&gt;% dplyr::mutate(CHR = as.factor(CHR), BP = as.integer(BP))
    df_gr &lt;- GenomicRanges::makeGRangesFromDataFrame(df, keep.extra.columns = FALSE, 
        ignore.strand = TRUE, seqinfo = NULL, seqnames.field = &quot;CHR&quot;, 
        start.field = &quot;BP&quot;, end.field = &quot;BP&quot;, starts.in.df.are.0based = FALSE)
    df_gr &lt;- BSgenome::snpsByOverlaps(dbSNP, df_gr, minoverlap = 1L) %&gt;% 
        as.data.frame()
    combined &lt;- df_gr %&gt;% dplyr::rename(SNP = RefSNP_id, CHR = seqnames, 
        BP = pos) %&gt;% dplyr::right_join(df, by = c(&quot;CHR&quot;, &quot;BP&quot;)) %&gt;% 
        dplyr::select(-strand, -alleles_as_ambig)
    return(combined)
}
</pre>

<pre>&gt; head(PsychEncode_filtered_tQTL)
     transcript_id gene_chr gene_start  gene_end strand number_of_SNPs_tested
1: ENST00000389484     chr2  142889270 142889270      +                  4426
2: ENST00000389484     chr2  142889270 142889270      +                  4426
3: ENST00000389484     chr2  142889270 142889270      +                  4426
4: ENST00000389484     chr2  142889270 142889270      +                  4426
5: ENST00000389484     chr2  142889270 142889270      +                  4426
6: ENST00000389484     chr2  142889270 142889270      +                  4426
   SNP_distance_to_TSS      SNP_id CHR        BP SNP_chr SNP_start   SNP_end
1:             -653810 2:142235460   2 142235460    chr2 142235460 142235460
2:              -93077 2:142796193   2 142796193    chr2 142796193 142796193
3:              -92821 2:142796449   2 142796449    chr2 142796449 142796449
4:              -86184 2:142803086   2 142803086    chr2 142803086 142803086
5:              -84480 2:142804790   2 142804790    chr2 142804790 142804790
6:              -82981 2:142806289   2 142806289    chr2 142806289 142806289
   nominal_pval regression_slope top_SNP          FDR            Gene
1:  2.68165e-06       -0.4458430       0 0.0006392623 ENSG00000168702
2:  9.96995e-07        0.0618155       0 0.0002597948 ENSG00000168702
3:  7.05439e-07        0.0637447       0 0.0001893377 ENSG00000168702
4:  1.23675e-06        0.0608933       0 0.0003162441 ENSG00000168702
5:  6.40556e-07        0.0635402       0 0.0001733051 ENSG00000168702
6:  1.22708e-06        0.0608389       0 0.0003139940 ENSG00000168702
   hgnc_symbol
1:       LRP1B
2:       LRP1B
3:       LRP1B
4:       LRP1B
5:       LRP1B
6:       LRP1B

</pre><pre>&gt; prueba = convert_loc_to_rs(df = PsychEncode_filtered_tQTL, dbSNP = dbSNP)
Error: Can&apos;t subset columns that don&apos;t exist.
<font color="#CC0000">✖</font> Column `strand` doesn&apos;t exist.
</pre>

<pre>&gt; prueba = PsychEncode_filtered_tQTL %&gt;% dplyr::select(-strand) %&gt;% convert_loc_to_rs(., dbSNP = dbSNP)
</pre>

<pre>&gt; head(prueba)
  CHR        BP         SNP   transcript_id gene_chr gene_start  gene_end
1   2 142235460 rs140967937 ENST00000389484     chr2  142889270 142889270
2   2 142796193   rs1449490 ENST00000389484     chr2  142889270 142889270
3   2 142796449   rs1868544 ENST00000389484     chr2  142889270 142889270
4   2 142803086   rs1449495 ENST00000389484     chr2  142889270 142889270
5   2 142804790  rs13036224 ENST00000389484     chr2  142889270 142889270
6   2 142806289   rs7605112 ENST00000389484     chr2  142889270 142889270
  number_of_SNPs_tested SNP_distance_to_TSS      SNP_id SNP_chr SNP_start
1                  4426             -653810 2:142235460    chr2 142235460
2                  4426              -93077 2:142796193    chr2 142796193
3                  4426              -92821 2:142796449    chr2 142796449
4                  4426              -86184 2:142803086    chr2 142803086
5                  4426              -84480 2:142804790    chr2 142804790
6                  4426              -82981 2:142806289    chr2 142806289
    SNP_end nominal_pval regression_slope top_SNP          FDR            Gene
1 142235460  2.68165e-06       -0.4458430       0 0.0006392623 ENSG00000168702
2 142796193  9.96995e-07        0.0618155       0 0.0002597948 ENSG00000168702
3 142796449  7.05439e-07        0.0637447       0 0.0001893377 ENSG00000168702
4 142803086  1.23675e-06        0.0608933       0 0.0003162441 ENSG00000168702
5 142804790  6.40556e-07        0.0635402       0 0.0001733051 ENSG00000168702
6 142806289  1.22708e-06        0.0608389       0 0.0003139940 ENSG00000168702
  hgnc_symbol
1       LRP1B
2       LRP1B
3       LRP1B
4       LRP1B
5       LRP1B
6       LRP1B
</pre>

**Comment by RHReynolds** [comment]
Thanks for the suggestion. I've already implemented a version of this in RHReynolds/colochelpR#2.
