### ISSUE TITLE
Scripts missing

### ISSUE THREAD

**Issue by Sandyyy123** [RHReynolds/colochelpR#6]
Hi,
Thank you for your work. I did your scripts earlier to perform colocalization and wanted to repeat it. But this time, I am unable to find the script: https://rhreynolds.github.io/scripts/coloc_RBD_eQTLGen.R.

**Comment by RHReynolds** [comment]
Hi Sandeep,

I believe the script you’re referring is in the linked repository found in the [Usage example](https://github.com/RHReynolds/colochelpR#usage-example) section of colochelpR’s README.md.

Best,
Regina

**Comment by Sandyyy123** [comment]
Hi Regina,
Thanks for prompt response. You have used these scripts for formatting
expression datasets. I can't find them in the usage example section.
https://rhreynolds.github.io/RBD-GWAS-analysis/RBD_coloc.html
Section 3.2: coloc_RBD_eQTLGen.R
<https://rhreynolds.github.io/scripts/coloc_RBD_eQTLGen.R>
Section 3.3. coloc_RBD_psychencode.R
<https://rhreynolds.github.io/scripts/coloc_RBD_psychencode.R>
Regards
*Sandeep Grover *

**Comment by RHReynolds** [comment]
Hi Sandeep,

You can find both scripts in the [scripts](https://github.com/RHReynolds/RBD-GWAS-analysis/tree/main/scripts) directory of the  repository linked in the usage example.

Best,
Regina

**Comment by Sandyyy123** [comment]
Great, thanks a lot.
Regards
*Sandeep Grover *
